name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

  workflow_dispatch:
    inputs:
      action:
        description: 'Action to be performed by Terraform'
        required: true
        default: 'apply'
        options:
          - 'apply'
          - 'destroy'

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./terraform

jobs:
  dev_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terraform workspace select or create dev
        run: terraform workspace select dev || terraform workspace new dev
        working-directory: ${{ env.WORKING_DIR }}
      
      - name: Terraform apply dev
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
    
      - name: Terraform destroy dev
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}

  stage_prod:
    needs: dev_stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terraform workspace select or create stage
        run: terraform workspace select stage || terraform workspace new stage
        working-directory: ${{ env.WORKING_DIR }}
      
      - name: Terraform apply stage
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
    
      - name: Terraform destroy stage
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}

  prod:
    needs: stage_prod
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terraform workspace select or create prod
        run: terraform workspace select prod || terraform workspace new prod
        working-directory: ${{ env.WORKING_DIR }}
      
      - name: Terraform apply prod
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
    
      - name: Terraform destroy prod
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
